language: node_js
install:
  - npm install -g codecov
node_js:
  - "node"
  - "lts/*"
cache:
  directories:
    - "node_modules"
script:
  - yarn install
  - yarn audit
  - ./bin/validate_browser.sh
  - yarn run lint
  - yarn test
  - codecov
